[package]
name = "amf-rs"
version = "0.1.0"
edition = "2024"
description = "ğŸ¦€ Rust implementation of Action Message Format (AMF) protocol."
authors = ["ubizhang@hotmail.com"]
license = "GPL-3.0-or-later"
repository = "https://github.com/F2077/amf-rs"

[dependencies]
indexmap = "2.10.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
itertools = "0.10.5"
paste = "1.0"
which = "8.0.0"
regex = "1.11.1"
once_cell = "1.21.3"

[features]
default = []
bench = []  # æ˜¾å¼å£°æ˜ bench ç‰¹æ€§

#[[bench]]
#name = "utf8_benchmark"
#harness = false

